services:
  mongo:
    image: mongo:latest
    container_name: Team_Hub_DB
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: teamHubUser
      MONGO_INITDB_ROOT_PASSWORD: teamHubPass

  redis:
    image: redis:alpine
    container_name: Team_Hub_Redis
    ports:
      - 6379:6379
